#!/usr/bin/env python3

import re, sys

message_file = open(sys.argv[1], "r")
message = message_file.readline()

regex = r"^(fix|feat|BREAKING CHANGE|chore|docs|style|refactor|perf|test|improvement)(\(\w+\))?: \w+.*$"

matches = re.search(regex, message)

if not matches:
    print ("\033[93m Commit message not follow Conventional Commits \033[0m")
    exit(1)
