#!/usr/bin/env python3

import re, sys

message_file = open(sys.argv[1], "r")
message = message_file.readline()

regex = r"^(fix|feat|BREAKING CHANGE|chore|docs|style|refactor|perf|test|improvement)(\(\w+\))?: \w+.*$"

matches = re.search(regex, message)

if not matches:
    print ("\033[93mWarning:\nCommit message not follow Conventional Commits")
    print ("Please follow this convention: https://www.conventionalcommits.org/en/v1.0.0/ \033[0m")
    exit(1)
